name: Azure Static Web App IaC

on: 
  workflow_dispatch


env:
  STATICWEBAPPNAME: rubicon-devday-swa

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ secrets.AZURE_RESOURCEGROUP }}
          template: ./infra/staticwebapp.bicep
          parameters: staticwebappname="${{ env.STATICWEBAPPNAME }}"
