on:
  issues:
    types: [opened, labeled]

jobs:
  apply-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        if: github.event.action == 'opened'
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['Triage']
            })

      - name: Add issue to project board
        if: contains(github.event.issue.labels.*.name, 'Triage')
        uses: actions/github-script@v6
        with:
          script: |
            github.projects.createCard({
              project-name: "Rubicon Demo Project",
              column-name: "Title",
              content_id: context.payload.issue.id,
              content_type: "Issue"
            });
