name: PR flow WebApp

on: 
  pull_request:
    types: [ opened, synchronize, closed ] 

env:
  APPNAME: rubicon-devday-app
  SLOTNAME: ${{ github.event.number }}

jobs:
  create-slot:
    if: github.event.action == 'opened'
    runs-on:  ubuntu-latest
    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - run: az webapp deployment slot create --resource-group ${{ secrets.AZURE_RESOURCEGROUP }} --name ${{ env.APPNAME }} --slot ${{ env.SLOTNAME }}

  deploy-webapp:
    needs: create-slot
    runs-on: ubuntu-latest
    if: always() && github.event.action != 'closed'
    steps:
      - name: Comment Pull Request
        uses: thollander/actions-comment-pull-request@v1
        with:
          # Message that should be printed in the pull request
          message: Awaiting deployment...
          comment_includes: 'Created staging environment - https://${{ env.APPNAME }}-${{ env.SLOTNAME }}.azurewebsites.net/'
          # Github token of the repository (automatically created by Github)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v2.3.4
        
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}           

      - name: Deploy Web App
        uses: Azure/webapps-deploy@v2
        with:
          app-name: ${{ env.APPNAME }}
          package: ./src
          slot-name: ${{ env.SLOTNAME }}
     
      - name: Comment Pull Request
        uses: thollander/actions-comment-pull-request@v1
        with:
          # Message that should be printed in the pull request
          message: Created staging environment - https://${{ env.APPNAME }}-${{ env.SLOTNAME }}.azurewebsites.net/
          # Replace placeholder
          comment_includes: 'Awaiting deployment...'
          # Github token of the repository (automatically created by Github)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  remove-slot:
    runs-on: ubuntu-latest
    if: github.event.action == 'closed'
    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}   
          
      - run: az webapp deployment slot delete --resource-group ${{ secrets.AZURE_RESOURCEGROUP }} --name ${{ env.APPNAME }} --slot ${{ env.SLOTNAME }}
