name: PR flow Static Web App

on: 
  pull_request:
    types: [ opened, reopened ] 

env:
  STATICWEBAPPNAME: rubicon-devday-swa

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get SWA deployment token
        uses: azure/CLI@v1
        with:
            inlineScript: |
                SWA_DEPLOYMENT_TOKEN=$(az staticwebapp secrets list -n ${{ secrets.SWA_NAME }} -o tsv --query properties.apiKey)
                echo "::add-mask::$SWA_DEPLOYMENT_TOKEN"
                echo SWA_DEPLOYMENT_TOKEN=$SWA_DEPLOYMENT_TOKEN >> $GITHUB_ENV

      - name: Deploy Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
            azure_static_web_apps_api_token: ${{ env.SWA_DEPLOYMENT_TOKEN }}
            repo_token: ${{ secrets.GITHUB_TOKEN }}
            action: "upload"
            skip_app_build: true
            app_location: ./src
