name: PR flow Static Web App

on: 
  pull_request:
    types: [ opened, reopened, synchronize, closed ] 

env:
  APPNAME: rubicon-devday-app
  SLOTNAME: ${{ github.event.number }}

jobs:
  build-and-deploy:
    if: github.event.action != 'closed'
    env: 
      APPNAME: rubicon-devday-swa
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get SWA deployment token
        uses: azure/CLI@v1
        with:
            inlineScript: |
                SWA_DEPLOYMENT_TOKEN=$(az staticwebapp secrets list -n ${{ secrets.SWA_NAME }} -o tsv --query properties.apiKey)
                echo "::add-mask::$SWA_DEPLOYMENT_TOKEN"
                echo SWA_DEPLOYMENT_TOKEN=$SWA_DEPLOYMENT_TOKEN >> $GITHUB_ENV

      - name: Deploy Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
            azure_static_web_apps_api_token: ${{ env.SWA_DEPLOYMENT_TOKEN }}
            repo_token: ${{ secrets.GITHUB_TOKEN }}
            action: "upload"
            skip_app_build: true
            app_location: ./src
  
  create-slot:
    if: github.event.action == 'opened'
    runs-on:  ubuntu-latest
    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - run: az webapp deployment slot create --resource-group ${{ secrets.AZURE_RESOURCEGROUP }} --name ${{ env.APPNAME }} --slot ${{ env.SLOTNAME }}

  deploy-webapp:
    needs: create-slot
    runs-on: ubuntu-latest
    if: always() && github.event.action != 'closed' && github.event.action != 'opened'
    steps:
      - name: Comment Pull Request
        uses: thollander/actions-comment-pull-request@v1
        with:
          # Message that should be printed in the pull request
          message: Awaiting deployment...
          # Github token of the repository (automatically created by Github)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v2.3.4
        
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}           

      - name: Deploy Web App
        uses: Azure/webapps-deploy@v2
        with:
          app-name: ${{ env.APPNAME }}
          package: ./src
          slot-name: ${{ env.SLOTNAME }}
     
      - name: Comment Pull Request
        uses: thollander/actions-comment-pull-request@v1
        with:
          # Message that should be printed in the pull request
          message: Created staging environment - https://${{ env.APPNAME }}-${{ env.SLOTNAME }}.azurewebsites.net/
          # Replace placeholder
          comment_includes: 'Awaiting deployment...'
          # Github token of the repository (automatically created by Github)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  remove-slot:
    if: github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}   
          
      - run: az webapp deployment slot delete --resource-group ${{ secrets.AZURE_RESOURCEGROUP }} --name ${{ env.APPNAME }} --slot ${{ env.SLOTNAME }}